// Code generated by internal/cmd/specsync; DO NOT EDIT.

package spec

// PinnedSpecVersion is the PandaDoc OpenAPI version this SDK is synced against.
const PinnedSpecVersion = "7.18.0"

// CoveredOperations is the exact operation manifest supported by this SDK milestone.
var CoveredOperations = []Operation{
	{Method: "GET", Path: "/public/v1/documents", OperationID: "listDocuments", Tag: "Documents"},
	{Method: "POST", Path: "/public/v1/documents", OperationID: "createDocument", Tag: "Documents"},
	{Method: "PATCH", Path: "/public/v1/documents/ownership", OperationID: "transferAllDocumentsOwnership", Tag: "Documents"},
	{Method: "GET", Path: "/public/v1/documents/{document_id}/esign-disclosure", OperationID: "documentESignDisclosure", Tag: "Documents"},
	{Method: "DELETE", Path: "/public/v1/documents/{id}", OperationID: "deleteDocument", Tag: "Documents"},
	{Method: "GET", Path: "/public/v1/documents/{id}", OperationID: "statusDocument", Tag: "Documents"},
	{Method: "PATCH", Path: "/public/v1/documents/{id}", OperationID: "updateDocument", Tag: "Documents"},
	{Method: "POST", Path: "/public/v1/documents/{id}/append-content-library-item", OperationID: "appendContentLibraryItemToDocument", Tag: "Documents"},
	{Method: "GET", Path: "/public/v1/documents/{id}/details", OperationID: "detailsDocument", Tag: "Documents"},
	{Method: "GET", Path: "/public/v1/documents/{id}/download", OperationID: "downloadDocument", Tag: "Documents"},
	{Method: "GET", Path: "/public/v1/documents/{id}/download-protected", OperationID: "downloadProtectedDocument", Tag: "Documents"},
	{Method: "POST", Path: "/public/v1/documents/{id}/draft", OperationID: "documentRevertToDraft", Tag: "Documents"},
	{Method: "POST", Path: "/public/v1/documents/{id}/editing-sessions", OperationID: "createDocumentEditingSession", Tag: "Documents"},
	{Method: "POST", Path: "/public/v1/documents/{id}/move-to-folder/{folder_id}", OperationID: "documentMoveToFolder", Tag: "Documents"},
	{Method: "PATCH", Path: "/public/v1/documents/{id}/ownership", OperationID: "transferDocumentOwnership", Tag: "Documents"},
	{Method: "POST", Path: "/public/v1/documents/{id}/send", OperationID: "sendDocument", Tag: "Documents"},
	{Method: "POST", Path: "/public/v1/documents/{id}/session", OperationID: "createDocumentLink", Tag: "Documents"},
	{Method: "PATCH", Path: "/public/v1/documents/{id}/status", OperationID: "changeDocumentStatus", Tag: "Documents"},
	{Method: "PATCH", Path: "/public/v1/documents/{id}/status?upload", OperationID: "changeDocumentStatusWithUpload", Tag: "Documents"},
	{Method: "POST", Path: "/public/v1/documents?upload", OperationID: "createDocumentFromUpload", Tag: "Documents"},
	{Method: "POST", Path: "/oauth2/access_token", OperationID: "accessToken", Tag: "OAuth 2.0 Authentication"},
	{Method: "POST", Path: "/public/v2/product-catalog/items", OperationID: "createCatalogItem", Tag: "Product catalog"},
	{Method: "GET", Path: "/public/v2/product-catalog/items/search", OperationID: "searchCatalogItems", Tag: "Product catalog"},
	{Method: "DELETE", Path: "/public/v2/product-catalog/items/{item_uuid}", OperationID: "deleteCatalogItem", Tag: "Product catalog"},
	{Method: "GET", Path: "/public/v2/product-catalog/items/{item_uuid}", OperationID: "getCatalogItem", Tag: "Product catalog"},
	{Method: "PATCH", Path: "/public/v2/product-catalog/items/{item_uuid}", OperationID: "updateCatalogItem", Tag: "Product catalog"},
	{Method: "GET", Path: "/public/v1/webhook-events", OperationID: "listWebhookEvent", Tag: "Webhook events"},
	{Method: "GET", Path: "/public/v1/webhook-events/{id}", OperationID: "detailsWebhookEvent", Tag: "Webhook events"},
	{Method: "GET", Path: "/public/v1/webhook-subscriptions", OperationID: "listWebhookSubscriptions", Tag: "Webhook subscriptions"},
	{Method: "POST", Path: "/public/v1/webhook-subscriptions", OperationID: "createWebhookSubscription", Tag: "Webhook subscriptions"},
	{Method: "DELETE", Path: "/public/v1/webhook-subscriptions/{id}", OperationID: "deleteWebhookSubscription", Tag: "Webhook subscriptions"},
	{Method: "GET", Path: "/public/v1/webhook-subscriptions/{id}", OperationID: "detailsWebhookSubscription", Tag: "Webhook subscriptions"},
	{Method: "PATCH", Path: "/public/v1/webhook-subscriptions/{id}", OperationID: "updateWebhookSubscription", Tag: "Webhook subscriptions"},
	{Method: "PATCH", Path: "/public/v1/webhook-subscriptions/{id}/shared-key", OperationID: "updateWebhookSubscriptionSharedKey", Tag: "Webhook subscriptions"},
}
